services:
  reservation_api:
    container_name: reservation_api
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - reservation_db
    volumes:
      - .:/app
    env_file:
      - .env
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - '8000:8000'

  reservation_db:
    container_name: reservation_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - reservation_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  reservation_db:
